//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w3_group_1_client.ContactExample {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInformation", Namespace="http://schemas.datacontract.org/2004/07/w3_group_1")]
    [System.SerializableAttribute()]
    public partial class ContactInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressField, value) != true)) {
                    this.emailAddressField = value;
                    this.RaisePropertyChanged("emailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.faxNumberField, value) != true)) {
                    this.faxNumberField = value;
                    this.RaisePropertyChanged("faxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactExample.IContactManager")]
    public interface IContactManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetContactInformation", ReplyAction="http://tempuri.org/IContactManager/GetContactInformationResponse")]
        w3_group_1_client.ContactExample.ContactInformation GetContactInformation(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetContactInformation", ReplyAction="http://tempuri.org/IContactManager/GetContactInformationResponse")]
        System.Threading.Tasks.Task<w3_group_1_client.ContactExample.ContactInformation> GetContactInformationAsync(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetNumberOfContacts", ReplyAction="http://tempuri.org/IContactManager/GetNumberOfContactsResponse")]
        int GetNumberOfContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactManager/GetNumberOfContacts", ReplyAction="http://tempuri.org/IContactManager/GetNumberOfContactsResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfContactsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactManagerChannel : w3_group_1_client.ContactExample.IContactManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactManagerClient : System.ServiceModel.ClientBase<w3_group_1_client.ContactExample.IContactManager>, w3_group_1_client.ContactExample.IContactManager {
        
        public ContactManagerClient() {
        }
        
        public ContactManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public w3_group_1_client.ContactExample.ContactInformation GetContactInformation(string lastName) {
            return base.Channel.GetContactInformation(lastName);
        }
        
        public System.Threading.Tasks.Task<w3_group_1_client.ContactExample.ContactInformation> GetContactInformationAsync(string lastName) {
            return base.Channel.GetContactInformationAsync(lastName);
        }
        
        public int GetNumberOfContacts() {
            return base.Channel.GetNumberOfContacts();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfContactsAsync() {
            return base.Channel.GetNumberOfContactsAsync();
        }
    }
}
