//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w3_lab_3_client.BankingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInformation", Namespace="http://schemas.datacontract.org/2004/07/w3_lab_3")]
    [System.SerializableAttribute()]
    public partial class AccountInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentAmount {
            get {
                return this.CurrentAmountField;
            }
            set {
                if ((this.CurrentAmountField.Equals(value) != true)) {
                    this.CurrentAmountField = value;
                    this.RaisePropertyChanged("CurrentAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankingService.IBankingService")]
    public interface IBankingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/ReturnAmountEarned", ReplyAction="http://tempuri.org/IBankingService/ReturnAmountEarnedResponse")]
        float ReturnAmountEarned(float balance, float interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/ReturnAmountEarned", ReplyAction="http://tempuri.org/IBankingService/ReturnAmountEarnedResponse")]
        System.Threading.Tasks.Task<float> ReturnAmountEarnedAsync(float balance, float interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/GetAccountInformation", ReplyAction="http://tempuri.org/IBankingService/GetAccountInformationResponse")]
        w3_lab_3_client.BankingService.AccountInformation[] GetAccountInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/GetAccountInformation", ReplyAction="http://tempuri.org/IBankingService/GetAccountInformationResponse")]
        System.Threading.Tasks.Task<w3_lab_3_client.BankingService.AccountInformation[]> GetAccountInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankingServiceChannel : w3_lab_3_client.BankingService.IBankingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankingServiceClient : System.ServiceModel.ClientBase<w3_lab_3_client.BankingService.IBankingService>, w3_lab_3_client.BankingService.IBankingService {
        
        public BankingServiceClient() {
        }
        
        public BankingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float ReturnAmountEarned(float balance, float interest) {
            return base.Channel.ReturnAmountEarned(balance, interest);
        }
        
        public System.Threading.Tasks.Task<float> ReturnAmountEarnedAsync(float balance, float interest) {
            return base.Channel.ReturnAmountEarnedAsync(balance, interest);
        }
        
        public w3_lab_3_client.BankingService.AccountInformation[] GetAccountInformation() {
            return base.Channel.GetAccountInformation();
        }
        
        public System.Threading.Tasks.Task<w3_lab_3_client.BankingService.AccountInformation[]> GetAccountInformationAsync() {
            return base.Channel.GetAccountInformationAsync();
        }
    }
}
